/*
 * This source file was generated by the Gradle 'init' task
 */
package junit_gradle_empty;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void Main(String[] args) {
    	
    	System.out.println("Rodou o projeto");
    	
    }
}
